"""add_reading_progress

Revision ID: 368ec4f939ff
Revises: 66b920a99afe
Create Date: 2025-12-26 10:37:21.061123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368ec4f939ff'
down_revision: Union[str, None] = '66b920a99afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('location_label', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reading_progress_item', 'reading_progress', ['item_id'], unique=False)
    op.create_index('idx_reading_progress_last_read', 'reading_progress', ['last_read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reading_progress_last_read', table_name='reading_progress')
    op.drop_index('idx_reading_progress_item', table_name='reading_progress')
    op.drop_table('reading_progress')
    # ### end Alembic commands ###
