"""initial schema

Revision ID: 75b0e362b398
Revises: 
Create Date: 2025-12-23 11:31:44.048444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75b0e362b398'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['classifications.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_classifications_parent', 'classifications', ['parent_code'], unique=False)
    op.create_index('idx_classifications_system', 'classifications', ['system'], unique=False)
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_name', sa.String(length=255), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_creators_name', 'creators', ['name'], unique=False)
    op.create_index('idx_creators_sort', 'creators', ['sort_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collections_public', 'collections', ['is_public'], unique=False, postgresql_where='is_public = true')
    op.create_index('idx_collections_user', 'collections', ['user_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('sort_title', sa.String(length=500), nullable=True),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('classification_code', sa.String(length=20), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('isbn13', sa.String(length=20), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('series_name', sa.String(length=255), nullable=True),
    sa.Column('series_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['classification_code'], ['classifications.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_items_classification', 'items', ['classification_code'], unique=False)
    op.create_index('idx_items_isbn', 'items', ['isbn'], unique=False)
    op.create_index('idx_items_isbn13', 'items', ['isbn13'], unique=False)
    op.create_index('idx_items_media_type', 'items', ['media_type'], unique=False)
    op.create_index('idx_items_search', 'items', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_items_series', 'items', ['series_name'], unique=False)
    op.create_index('idx_items_tags', 'items', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('collection_items',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'item_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_md5', sa.String(length=32), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('metadata_extracted', sa.Boolean(), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('idx_files_checksum', 'files', ['checksum_md5'], unique=False)
    op.create_index('idx_files_format', 'files', ['format'], unique=False)
    op.create_index('idx_files_item', 'files', ['item_id'], unique=False)
    op.create_table('item_creators',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'creator_id', 'role')
    )
    op.create_index('idx_item_creators_creator', 'item_creators', ['creator_id'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(length=2000), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_md5', sa.String(length=32), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('migrated_file_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('extracted_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'migrated', 'duplicate', 'failed', 'skipped')", name='valid_status'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['source_files.id'], ),
    sa.ForeignKeyConstraint(['migrated_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path')
    )
    op.create_index('idx_source_files_checksum', 'source_files', ['checksum_md5'], unique=False)
    op.create_index('idx_source_files_format', 'source_files', ['format'], unique=False)
    op.create_index('idx_source_files_status', 'source_files', ['status'], unique=False)
    op.create_table('user_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_index('idx_progress_last', 'user_progress', ['last_accessed'], unique=False)
    op.create_index('idx_progress_user', 'user_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_progress_user', table_name='user_progress')
    op.drop_index('idx_progress_last', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index('idx_source_files_status', table_name='source_files')
    op.drop_index('idx_source_files_format', table_name='source_files')
    op.drop_index('idx_source_files_checksum', table_name='source_files')
    op.drop_table('source_files')
    op.drop_index('idx_item_creators_creator', table_name='item_creators')
    op.drop_table('item_creators')
    op.drop_index('idx_files_item', table_name='files')
    op.drop_index('idx_files_format', table_name='files')
    op.drop_index('idx_files_checksum', table_name='files')
    op.drop_table('files')
    op.drop_table('collection_items')
    op.drop_index('idx_items_tags', table_name='items', postgresql_using='gin')
    op.drop_index('idx_items_series', table_name='items')
    op.drop_index('idx_items_search', table_name='items', postgresql_using='gin')
    op.drop_index('idx_items_media_type', table_name='items')
    op.drop_index('idx_items_isbn13', table_name='items')
    op.drop_index('idx_items_isbn', table_name='items')
    op.drop_index('idx_items_classification', table_name='items')
    op.drop_table('items')
    op.drop_index('idx_collections_user', table_name='collections')
    op.drop_index('idx_collections_public', table_name='collections', postgresql_where='is_public = true')
    op.drop_table('collections')
    op.drop_table('users')
    op.drop_index('idx_creators_sort', table_name='creators')
    op.drop_index('idx_creators_name', table_name='creators')
    op.drop_table('creators')
    op.drop_index('idx_classifications_system', table_name='classifications')
    op.drop_index('idx_classifications_parent', table_name='classifications')
    op.drop_table('classifications')
    # ### end Alembic commands ###
