"""add_system_piles

Revision ID: c1fc57423096
Revises: 368ec4f939ff
Create Date: 2025-12-26 12:05:40.637819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fc57423096'
down_revision: Union[str, None] = '368ec4f939ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('is_system', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('collections', sa.Column('system_key', sa.String(length=50), nullable=True))
    op.create_index('idx_collections_system_key', 'collections', ['user_id', 'system_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_collections_system_key', table_name='collections')
    op.drop_column('collections', 'system_key')
    op.drop_column('collections', 'is_system')
    # ### end Alembic commands ###
