"""add_backdrop_path

Revision ID: cd19c4aa26ac
Revises: f873c1cadc3d
Create Date: 2025-12-26 10:21:05.414436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd19c4aa26ac'
down_revision: Union[str, None] = 'f873c1cadc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('backdrop_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'backdrop_path')
    # ### end Alembic commands ###
